version: '3'

services:
  nginxserver:
    build: ./nginx
    ports:
      - "7003:80"
    depends_on:
      - app1
      - app2
    networks:
      - LoadBalancerNet

  app1:
    build: ./app1
    ports:
      - "7001:80"
    networks:
      - LoadBalancerNet

  app2:
    build: ./app2
    ports:
      - "7002:80"
    networks:
      - LoadBalancerNet
networks:
  LoadBalancerNet: