version: '3'

services:
  proxy:
    image: nginx:latest
    volumes:
      - ./nginx/:/etc/nginx/conf.d/:ro
      - ./proxy/:/usr/share/nginx/html/:ro
    ports:
      - "80:80"
    networks:
      - internal-network
    
  app1:
    image: nginx:latest
    volumes:
      - ./app1/:/usr/share/nginx/html/:ro
    ports:
      - "7006:80"
    networks:
      - internal-network
    
  
  app2:
    image: nginx:latest
    volumes:
      - ./app2/:/usr/share/nginx/html/:ro
    ports:
      - "7007:80"
    networks:
      - internal-network
    
  app3:
    image: nginx:latest
    volumes:
      - ./app3/:/usr/share/nginx/html/:ro
    ports:
      - "7008:80"
    networks:
      - internal-network
 
networks:
  internal-network:
