version: '3'

services:
  proxy:
    image: nginx:latest
    volumes:
      - ./proxy/:/etc/nginx/conf.d/:ro
    ports:
      - "8080:80"
    networks:
      - internal-network
    
  app1:
    image: nginx:latest
    volumes:
      - ./app1/:/usr/share/nginx/html/:ro
    ports:
      - "8081:80"
    networks:
      - internal-network
    
  
  app2:
    image: nginx:latest
    volumes:
      - ./app2/:/usr/share/nginx/html/:ro
    ports:
      - "8082:80"
    networks:
      - internal-network
    
  app3:
    image: nginx:latest
    volumes:
      - ./app3/:/usr/share/nginx/html/:ro
    ports:
      - "8083:80"
    networks:
      - internal-network
 
networks:
  internal-network:
