- name: Kubernetes
  hosts: all
  become: true

  tasks:
    - name: Disable Swap
      command: swapoff -a
      ignore_errors: yes

    - name: Remove Swap Entry from /etc/fstab
      lineinfile:
        path: /etc/fstab
        state: absent
        regexp: '^/swapfile'

    - name: Remove Swap File
      file:
        path: /swapfile
        state: absent

    - name: Overlay Module
      command: modprobe overlay

    - name: br_netfilter Module
      command: modprobe br_netfilter

    - name: Creating a file with content
      copy:
        dest: "/etc/sysctl.d/k8s.conf"
        content: |
          net.bridge.bridge-nf-call-ip6tables = 1
          net.bridge.bridge-nf-call-iptables = 1
          net.ipv4.ip_forward = 1
   
    - name: Apply sysctl
      command: sysctl -p /etc/sysctl.d/k8s.conf
    
    - name: Install containerd
      apt:
        name: containerd
        update_cache: yes
        state: present

    - name: Create containerd config directory
      file:
       path: /etc/containerd
       state: directory
    
    - name: Contanierd Config File
      ansible.builtin.shell: containerd config default > /etc/containerd/config.toml

    - name: Active Cgroup
      lineinfile:
        path: /etc/containerd/config.toml
        regexp: '^            SystemdCgroup '  # Değiştirilecek satırı bulma
        line: '            SystemdCgroup = true' # Değiştirilecek satır

    - name: Restart Containerd
      ansible.builtin.systemd_service:
         state: restarted
         daemon_reload: true
         name: containerd

    - name: Add Kubernetes GPG key
      shell: |
        curl -fsSL https://pkgs.k8s.io/core:/stable:/v1.31/deb/Release.key | sudo gpg --dearmor -o /etc/apt/keyrings/kubernetes-apt-keyring.gpg
        echo 'deb [signed-by=/etc/apt/keyrings/kubernetes-apt-keyring.gpg] https://pkgs.k8s.io/core:/stable:/v1.31/deb/ /' | sudo tee /etc/apt/sources.list.d/kubernetes.list

    - name: Install kubectl, kubeadm, kubelet
      apt:
        name:
          - kubectl
          - kubeadm
          - kubelet
        update_cache: yes
        state: present

    - name: Hold apt packages
      dpkg_selections:
        name: "{{ item }}"
        selection: hold
      loop:
        - kubectl
        - kubeadm
        - kubelet

