version: '2'

services:
  nginxserver:
    build: ./nginx
    ports:
      - "80:80"
    depends_on:
      - app1
      - app2

    
  app1:
    build: ./app1
    ports:
      - "3001:80"

  
  app2:
    build: ./app2
    ports:
      - "3002:80"

