version: '2'

services:
  nginx:
    build: ./nginx
    ports:
      - "7003:80"
    depends_on:
      - app_1
      - app_2
    
  app_1:
    build: ./app1
    ports:
      - "7001:80"
  
  app_2:
    build: ./app2
    ports:
      - "7002:80"