#This is example file
gcp:
  children:
    kubernetes:
      hosts:
        master:
          ansible_host: 
          ansible_user: 
          ansible_ssh_private_key_file: 
        
        worker:
          ansible_host: 
          ansible_user: 
          ansible_ssh_private_key_file: 
        

       



