version: '2'

services:
  nginx_1:
    build: ./app1
    ports:
      - "7001:80"

  nginx_2:
    build: ./app2
    ports:
      - "7002:80"
    
  nginx_3:
    build: ./app3
    ports:
      - "5003:80"
